[versions]
junit = "6.1.3"
junit_platform = "6.1.3"
assertj = "3.27.7"
testcontainers = "2.0.5"

[libraries]
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit_platform" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }

[bundles]
testcontainers_junit = ["testcontainers", "testcontainers-junit"]
