blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/concosminx/paki-utils/discussions
    about: Use discussions if you have another issue, an idea for improvement or for asking questions.
